// packages/core/src/client/webcomponents/components/DockEmbedded.vue
<script setup lang="ts">
import type { DocksContext } from '@vitejs/devtools-kit/client'
import Dock from './Dock.vue'
import DockPanel from './DockPanel.vue'
import FloatingTooltip from './FloatingTooltip.vue'

defineProps<{
  context: DocksContext
}>()
</script>

<template>
  <Dock :context>
    <template #default="{ dockEl, panelMargins, selected }">
      <DockPanel
        :context
        :selected
        :dock-el="dockEl!"
        :panel-margins="panelMargins"
      />
    </template>
  </Dock>
  <FloatingTooltip />
</template>

// packages/core/src/client/webcomponents/components/DockEmbedded.ts
import type { DocksContext } from '@vitejs/devtools-kit/client'
import type { VueElementConstructor } from 'vue'
import { defineCustomElement } from 'vue'
import css from '../.generated/css'
import Component from './DockEmbedded.vue'

export const DockEmbedded = defineCustomElement(
  Component,
  {
    shadowRoot: true,
    styles: [css],
  },
) as VueElementConstructor<{
  context: DocksContext
}>

customElements.define('vite-devtools-dock-embedded', DockEmbedded)
